account:
  starting_equity_usd: 100000
bitget:
  api_key: ''
  api_secret: ''
  password: ''
db:
  path: data\db\ETH_USDT_5m.db
exchange: binance
fees:
  maker_fee_bps: 2
  spread_bps: 1
  taker_fee_bps: 5
ml:
  batch: 512
  dropout: 0.1
  epochs: 12
  hidden: 128
  horizon_bars: 12
  lr: 0.001
  p_entry: 0.6
mode: paper
risk:
  allow_shorts: true
  breakeven_at_R: 1.0
  sl_atr_mult: 2.2
  sl_tp_style: keltner
  trail_atr_mult: 2.0
  tp_rr_multiple: 2.0
  time_stop_bars: 96
  keltner_mult: 1.5
  max_daily_loss_pct: 2
  partial_tp_at_R: 1
  entry:
    long:
      entry_all:
      - indicator: atr14
        op: '>'
        rhs: 0.0
      entry_any:
      - indicator: rsi14
        op: <
        rhs: 35
      - indicator: close
        op: crosses_above
        rhs_indicator: dn55
    short:
      entry_all:
      - indicator: atr14
        op: '>'
        rhs: 0.0
      entry_any:
      - indicator: rsi14
        op: '>'
        rhs: 65
      - indicator: close
        op: crosses_below
        rhs_indicator: up55
sizing:
  leverage: 3
  max_margin_util_pct: 80
  mode: usd
  portfolio_pct: 1
  usd: 1000
symbol: ETH/USDT
timeframe: 5m
tuning:
  adx_len:
  - 14
  - 20
  - 28
  bb_k:
  - 2
  - 2.5
  - 3
  bb_len:
  - 20
  - 30
  breakeven_at_R:
  - 0.5
  - 1
  - 1.5
  cci_len:
  - 14
  - 20
  - 40
  donchian_n:
  - 20
  - 55
  - 100
  ema_fast:
  - 10
  - 20
  - 30
  ema_slow:
  - 50
  - 100
  - 150
  - 200
  keltner_len:
  - 20
  - 30
  keltner_mult:
  - 1.5
  - 2
  macd_fast:
  - 12
  macd_sig:
  - 9
  macd_slow:
  - 26
  rsi_buy:
  - 25
  - 30
  - 35
  rsi_len:
  - 5
  - 7
  - 14
  rsi_sell:
  - 65
  - 70
  - 75
  sl_atr_mult:
  - 1.5
  - 2
  - 2.5
  - 3
  sl_tp_style:
  - atr_fixed
  - atr_trailing
  - chandelier
  - supertrend
  - keltner
  - breakeven_then_trail
  stoch_d:
  - 3
  - 3
  - 5
  stoch_k:
  - 5
  - 9
  - 14
  supertrend_len:
  - 10
  - 14
  - 20
  supertrend_mult:
  - 2
  - 3
  - 4
  time_stop_bars:
  - 48
  - 96
  - 192
  tp_rr_multiple:
  - 1.5
  - 2
  - 2.5
  - 3
  trail_atr_mult:
  - 1
  - 1.5
  - 2
  - 2.5
