mode: paper
symbol: BTC/USDT:USDT
timeframe: 5m
db:
  path: data/db/BTC_USDT_USDT_5m.db
account:
  starting_equity_usd: 100000
fees:
  spread_bps: 1
  taker_fee_bps: 5
  maker_fee_bps: 2
sizing:
  mode: usd
  usd: 1000
  portfolio_pct: 1
  leverage: 3
  max_margin_util_pct: 80
risk:
  allow_shorts: true
  sl_tp_style: atr_fixed
  sl_atr_mult: 2
  tp_rr_multiple: 2
  breakeven_at_R: 1
  trail_atr_mult: 2
  partial_tp_at_R: 1
  time_stop_bars: 96
  max_daily_loss_pct: 2
bitget:
  api_key: ''
  api_secret: ''
  password: ''
ml:
  horizon_bars: 12
  hidden: 128
  dropout: 0.1
  lr: 0.001
  epochs: 12
  batch: 512
  p_entry: 0.6
tuning:
  ema_fast:
  - 10
  - 20
  - 30
  ema_slow:
  - 50
  - 100
  - 150
  - 200
  rsi_len:
  - 5
  - 7
  - 14
  rsi_buy:
  - 25
  - 30
  - 35
  rsi_sell:
  - 65
  - 70
  - 75
  adx_len:
  - 14
  - 20
  - 28
  donchian_n:
  - 20
  - 55
  - 100
  bb_len:
  - 20
  - 30
  bb_k:
  - 2
  - 2.5
  - 3
  stoch_k:
  - 5
  - 9
  - 14
  stoch_d:
  - 3
  - 3
  - 5
  cci_len:
  - 14
  - 20
  - 40
  macd_fast:
  - 12
  macd_slow:
  - 26
  macd_sig:
  - 9
  supertrend_len:
  - 10
  - 14
  - 20
  supertrend_mult:
  - 2
  - 3
  - 4
  keltner_len:
  - 20
  - 30
  keltner_mult:
  - 1.5
  - 2
  sl_tp_style:
  - atr_fixed
  - atr_trailing
  - chandelier
  - supertrend
  - keltner
  - breakeven_then_trail
  sl_atr_mult:
  - 1.5
  - 2
  - 2.5
  - 3
  tp_rr_multiple:
  - 1.5
  - 2
  - 2.5
  - 3
  breakeven_at_R:
  - 0.5
  - 1
  - 1.5
  trail_atr_mult:
  - 1
  - 1.5
  - 2
  - 2.5
  time_stop_bars:
  - 48
  - 96
  - 192
